Failing only thru openCPU interface with crytpic error below.  Since I switched to using RData files, guessing that 'lazyLoading' is the probelem--whatever that is.
Error:  .onLoad failed in loadNamespace() for 'later', details:
  call: NULL
  error: 'new_weakref' is not an exported object from 'namespace:rlang'✔ ~/Projects/EDCAT [feature/selectable-survey|…29⚑ 3]